### ISSUE TITLE
Core Dump Decyription // Hope This Project Goes Alive

### ISSUE THREAD

**Issue by itseyup** [louigi600/obash#15]
It has problems with core dump, install gdb; 
sudo apt-get install gdb
then run the script in the background;
`./Script.sh.x& ( gcore $! ) // This will create a core dump (Can be done without gcc)`
Then all the source code will be exposed.
There is an script which uses this obfuscator But his source code isn't exposed;
`wget git.io/HGMNetworkv5`

**Comment by louigi600** [comment]
This can't be truly fixed : the bash will at some point need to execute a normal decrypted script.
I'm not reimplemented bash, I'm just making it ever so slightly more difficult to read the script.
