### ISSUE TITLE
Cross compilation to arm

### ISSUE THREAD

**Issue by nightmare007** [louigi600/obash#5]
LABEL = HELP REQ

Hello,
I tried to compile this wonderfull tool for arm ( for android ), on my lubuntu 16.04 i368 - but with no success so far.

I ran the following
`sudo su`
`dpkg --add-architecture armhf`
`leafpad /etc/apt/sources.list`

*-> add:
`deb [arch=arm64,armhf] http://ports.ubuntu.com/ yakkety main restricted universe multiverse`
`deb [arch=arm64,armhf] http://ports.ubuntu.com/ yakkety-security main restricted universe multiverse`
`deb [arch=arm64,armhf] http://ports.ubuntu.com/ yakkety-backports main restricted universe multiverse`
*->save

`apt-get update`
`apt-get install aptitude`
`apt-get install make`
`apt-get install git`
`apt-get install crossbuild-essential-armhf`
`apt-get install gcc-arm-linux-gnueabihf`
`apt-get install libssl-dev:armhf`
`cd ~`
`git clone https://github.com/louigi600/obash`
`cd ./obash`
`CC=arm-linux-gnueabihf-gcc make`

When I run the last command I get an error:
`arm-linux-gnueabihf-gcc obash.c -o obash -lssl -lcrypto 
**/usr/lib/gcc-cross/arm-linux-gnueabihf/6/libgcc.a: file not recognized: File format not recognized**
collect2: error: ld returned 1 exit status
Makefile:10: recipe for target obash failed
make: *** [obash] Error 1`

**What am I doing wrong ?
should I install some form of gcc that's compatible with arm ?**

P.S, I also got android sdk installed and setup by running:
`export PATH=$PATH:/media/lubuntu/data/android-ndk-r10e/`

Lastly, since i'm foreign to compilation - it would be a GRAET HELP if you could please compile 'obash' to arm & arm64 and publish the binaries.
Thanks !

**Comment by louigi600** [comment]
Android isn't really a normal Linux distribution, It uses indeed the Linux kernel but the userland is very different from any normal GNU you would normally find.
