### ISSUE TITLE
very useful encryption tool, and i want to know how obash escaped the UNIX limit of ARG_MAX ?

### ISSUE THREAD

**Issue by wurenny** [louigi600/obash#6]
i got the max argument length limit on centos 7:
# getconf ARG_MAX
2097152

because that SHC has a bug about this limit(official), if the source shell script's size is too large, an error return when i execute the binary file which generate from shc:
Argument list too long: /bin/bash

and i found OBASH could work fine with my big size shell script, so i want to know how it escaped this limit ?

**Comment by louigi600** [comment]
Simple : I'm not passing the the decoded script as an argument.
Read the code for more details.

**Comment by louigi600** [comment]
Closing because this is a question not an issue.
